# Generated by Django 2.1.1 on 2018-09-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180911_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='fake_also',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='fake_one',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='fake_three',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='fake_two',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='not_fake',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestion'),
        ),
    ]
